[package]
authors = ["Pierre-Ã‰tienne Meunier <pe@pijul.org>"]
description = "Utilities to parse .ssh/config files, including helpers to implement ProxyCommand in Russh."
documentation = "https://docs.rs/russh-config"
edition = "2018"
include = ["Cargo.toml", "src/lib.rs", "src/proxy.rs"]
license = "Apache-2.0"
name = "russh-config"
repository = "https://github.com/warp-tech/russh"
version = "0.7.0"

[dependencies]
dirs-next = "2.0"
futures = "0.3"
log = "0.4"
thiserror = "1.0"
tokio = {version = "1.0", features = ["io-util", "net", "macros", "process"]}
whoami = "1.2"
